CREATE TABLE `new_table` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT userid CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`));

